---
title: "LabSea Protists"
author: "LabSea Slackers"
date: "`r Sys.Date()`"
output: html_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='figures/',
                      echo=TRUE, warning=FALSE, message=FALSE)

knitr::opts_knit$set(output.dir="reports")
```

```{r functions,echo=FALSE}
# functions needed to run the script
rm(list=ls(all=TRUE))

# get traits by otu
options(stringsAsFactors = FALSE)
#m=transect_seq_agg
#t=traits
#tSel="feeding_strategy"
#cw=cw_seq
#cw_var="validName"
# m = 
# t= taxonomic table rows= taxa, cols = taxa levels)
# tSel =  
# 
traitsByOTU<- function(m,t,tSel,cw,cw_var){
  v=rep(NA,ncol(m))
  names(v)=colnames(m)
  for(i in colnames(m)){
  tempName=as.character(cw[cw[,cw_var]%in%i,"validName"])

  if(length(which(t$validName%in%tempName))==0)next
    if(is.na(tempName))next
  v[i]=t[which(t$validName%in%tempName),tSel]
  }
  return(v)
}

logitPerCol<- function(m){
  for(i in 1:ncol(m)){
   m[,i]=logit(m[,i])}
  return(m)
}

#m=transect_seq_agg[,sizeClasses%in%"(0.2,2]"]
#c=as.factor(fsVector_seq)
# where m=community matrix (cols = taxa, rows = sites)
# c= a vertor with the selected taxonomic level for agregation and OTU as name
mergeByCat<- function(m,c){
  c=c[!is.na(c)]
  c=c[names(c)%in%colnames(m)]
  m=m[,names(c)]
  mergedM=matrix(NA,nrow(m),length(unique(c)),dimnames=list(rownames(m),unique(c)))
  for(i in unique(c)){
   mergedM[,i]=rowSums(m[,c%in%as.character(i),drop=F])}
  return(mergedM)
}

#function to output the correlations and significance from indval analysis
#factors=dat$stationGr
indval_outCor<-function(com=com, factors){
indval = strassoc(as.data.frame((com)), as.factor(factors), func = "r.g",nboot=999)
#df=round(cbind(indval$str[,1:length(unique(factors))],indval$sign[,(length(unique(factors))+2):(length(unique(factors))+3)]),2)
return(indval)}

waByOTU<-function(com,v){
  v=v[!is.na(v)]
  com=com[,names(v)]
  res=apply(com,1,function(x,v)sum(prop.table(x)*v),v=v)
  return(res)
}


plot_transect<- function(com,rep,colors=c("#73BAE6","#C7144C","#33a02c","#FFD700","#C742B5"),legend=T,ylim=c(0,0.8),f=0.7){
plot(com[,1]~rep,pch=16,col=colors[1],ylim=ylim,xlab="Days before peak",ylab="proportion",cex.lab=1.5,cex.axis=1.5,las=1,cex=1.7)
lines(lowess(com[,1]~rep, f = f), col =  colors[1],lwd=4)


for(i in 2:ncol(com)){
  points(com[,i]~rep,pch=16,col=colors[i],ylim=c(0,1),cex=1.7)
lines(lowess(com[,i]~rep, f =f), col = colors[i],lwd=4)
}
 op <- par(cex = 1.5)
if(legend)legend("topleft", legend=colnames(com),col=colors[1:ncol(com)],lty=1,lwd=3)
}

plot_transect_small<- function(com,rep,f=0.7){
  colors=c("#73BAE6","#C7144C","#33a02c","#FFD700","#C742B5")
plot(com[,1]~rep,pch=16,col=colors[1],ylim=c(min(com),max(com)),xlab="Days before peak",ylab="",cex.lab=1.5,cex.axis=1.5,las=1,cex=1.7)
lines(lowess(com[,1]~rep, f = 0.7), col = colors[1],lwd=4)


for(i in 2:ncol(com)){
  points(com[,i]~rep,pch=16,col=colors[i],ylim=c(0,1),cex=1.7)
lines(lowess(com[,i]~rep, f = f), col = colors[i],lwd=4)
}
 #op <- par(cex = 1.5)
#legend("topleft", legend=colnames(com),col=c("dodgerblue3","firebrick2","chartreuse3","darkmagenta","yellow")[1:ncol(com)],lty=1,lwd=3)
}

```

```{r packages,echo=F}
library(indicspecies)
library(vegan)
library(car)
library(plotrix)
library(plyr)
library(tidyr)
#-library(ggplot2)
library(knitr)
#-library(FD)
#library(ReporteRs)
```


```{r import and norm data, echo=F}

#import counts
transect_micro=read.csv("data/Microscopie_count_Hud2014_2015.csv",header=T,check.names=F)

#remove columns with an empty valid name
transect_micro=transect_micro[-which(transect_micro[,"validName"]==""),]

#sum by valid name
transect_micro=ddply(transect_micro, "validName", numcolwise(sum))

#transpose matrix (taxa as column)
transect_micro=t(transect_micro)
colnames(transect_micro)=transect_micro[1,];transect_micro=transect_micro[-1,]
transect_micro=as.data.frame(transect_micro)
rn=rownames(transect_micro)
transect_micro=apply(transect_micro, 2, as.numeric)
rownames(transect_micro)=rn

#import sequences data
transect_seq=read.csv("data/otu_transect_cnMod.csv",row.names=1)

#import traits
traits=read.csv("data/TransectTraitsTable_wide_03_2022.csv")
#traits=read.csv("data/TransectTraitsTable_wide.csv")


# import cross-walk tables for micro and sequencing
cw_micro=read.csv("data/cw_microscopie.csv")
cw_seq=read.csv("data/cw_sequencage.csv")

samdf=read.csv("data/samdf.csv",header=T,sep=",")

# match sites in sequences and samples
m=match(rownames(transect_seq),samdf$Sample)

# group samples by year and station (sum toghether fractions and depths)
groupVar=list(samdf[m,"Year"],samdf[m,"Station"])

transect_seq_agg=aggregate(transect_seq, by=groupVar,FUN=sum) 
rownames(transect_seq_agg)= apply( transect_seq_agg[,(1:length(groupVar))] , 1 , paste , collapse = "-" )
transect_seq_agg=transect_seq_agg[,-(1:length(groupVar))]


# match sites in microscopy and samples
m=match(rownames(transect_micro),samdf$Id)
# group samples by year and station (sum toghether fractions and depths)
groupVar=list(samdf[m,"Year"],samdf[m,"Station"])
transect_micro_agg=aggregate(transect_micro, by=groupVar,FUN=sum) 
rownames(transect_micro_agg)= apply( transect_micro_agg[,(1:length(groupVar))] , 1 , paste , collapse = "-" )
transect_micro_agg=transect_micro_agg[,-(1:length(groupVar))]

# import data gis for groups
data_gis=read.csv("data/DataGIS.csv")
rownames(data_gis)=apply(data_gis[,c("year","Station")] , 1 , paste , collapse = "-" )

gis_taxo=data_gis[,c("Chlorophyta","Dinoflagellata","Ochrophyta","Prymnesiophyceae")]

# aggregate samdf
# group samples by year and station (sum toghether fractions and depths)
groupVar=list(samdf$Year,samdf$Station)
samdf_agg=aggregate(samdf[,-c(1,2,5)], by=groupVar,FUN=mean) 
rownames(samdf_agg)= apply( samdf_agg[,(1:length(groupVar))] , 1 , paste , collapse = "-" )
samdf_agg=samdf_agg[,-(1:length(groupVar))]

# year as a factor
samdf_agg$Year=as.factor(samdf_agg$Year)

# group stations by water masses (3 or 4 masses)
samdf_agg$stationGr=cut(samdf_agg$Station,breaks=c(-Inf,11,27,Inf),labels=c("lss","centre","greenland"))


samdf_agg$stationGr=cut(samdf_agg$Station,breaks=c(-Inf,11,27,Inf),labels=c("lss","centre","greenland"))

#divide sequencing data by volume
transect_seq_agg=transect_seq_agg/samdf_agg[rownames(transect_seq_agg),"Volume"]
gis_taxo=gis_taxo/samdf_agg[rownames(gis_taxo),"Volume"]


write.csv(gis_taxo,"gis_taxo.csv")
colnames(data_gis)


# dummy coding
dummy=model.matrix(~stationGr, data = samdf_agg)
samdf_agg=cbind(samdf_agg,dummy)

# dummy coding
dummy=model.matrix(~Year, data = samdf_agg)
samdf_agg=cbind(samdf_agg,dummy)
```
```{r kable,echo=F}
# table of functional traits coverage
traitsSel=traits[,c("DMS","trophic_strategy","motility","Size_um")]
x=traitsSel$trophic_strategy
freqCol<-function(x){length(x[!is.na(x)])/length(x)}
sumTraits=as.matrix(apply(traitsSel,2,freqCol))
colnames(sumTraits)=c("Coverage")
kable(round(sumTraits[order(sumTraits,decreasing = T),,drop=F],2))

```



```{r taille moyenne, echo=F}
# create a size vector
sizeVector=traitsByOTU(transect_seq_agg,traits,"Size_um",cw_seq,"OTU.")
transect_meanSize=waByOTU(transect_seq_agg,sizeVector)

```
## Taxonomic 

Permanova for taxonomical composition (sequencing)
- Proportion of each taxa (to compare with functional) loggit transformed
```{r taxo, echo=F}

phylum=cw_seq$Phylum
names(phylum)=cw_seq$OTU.
transect_phylum=mergeByCat(transect_seq_agg,phylum)
transect_phylum=prop.table(as.matrix(transect_phylum),margin=1)

mean(rowSums(transect_phylum[,1:4]))
range(rowSums(transect_phylum[,1:4]))


dat=samdf_agg[rownames(transect_seq_agg),]
com=gis_taxo[rownames(dat),]
prop.table(as.matrix(gis_OTUtaxo),margin=1)


indval_outCor(com,factors=dat$Year)
indval_outCor(com,factors=dat$stationGr)



 
vp=varpart(com,cbind(dat$stationGrcentre,dat$stationGrgreenland),cbind(dat$Year2015,dat$Year2016))
plot(vp)

anova.cca(rda(com~cbind(dat$stationGrcentre,dat$stationGrgreenland)+dat$Year),by="margin",step=1000)
anova.cca(rda(com~cbind(dat$stationGrcentre,dat$stationGrgreenland)+dat$Year),step=1000) 

vp=varpart(com,cbind(dat$stationGrcentre,dat$stationGrgreenland),cbind(dat$Year2015,dat$Year2016),dat$DSP.4)
plot(vp)

anova.cca(rda(com~cbind(dat$stationGrcentre,dat$stationGrgreenland)+dat$DSP.4+dat$Year),by="margin",step=1000)
anova.cca(rda(com~cbind(dat$stationGrcentre,dat$stationGrgreenland)+dat$DSP.4+dat$Year),step=1000)


```



## Feeding strategy
- Proportion of organism/trait loggit transformed
```{r trophic_strategy seq, echo=F}


# create the feading strategy vector (fs)
fsVector=traitsByOTU(transect_seq_agg,traits,"trophic_strategy",cw_seq,"OTU.")
transect_fs=mergeByCat(transect_seq_agg,as.factor(fsVector))

rowSums(transect_fs)
rowSums(transect_seq_agg)
# calculate the proportion of each trait
com_prop=prop.table(as.matrix(transect_fs),margin=1)
com_abun=com_prop*rowSums(transect_fs)

samdf_agg=merge(samdf_agg,com_abun,by.x = "row.names",by.y = "row.names")
rownames(samdf_agg)=samdf_agg$Row.names;samdf_agg=samdf_agg[,-1]


dat=samdf_agg[rownames(transect_seq_agg),]
com=decostand(com_abun,method="hel")
indval_outCor(com,factors=dat$Year)
indval_outCor(com,factors=dat$stationGr)
#write.csv(indval_outCor(com,factors=dat$Year),"data/indVal_fs_yr.csv")
#write.csv(indval_outCor(com,factors=dat$stationGr),"data/indVal_fs_stations.csv")

  
vp=varpart(com,cbind(dat$stationGrcentre,dat$stationGrgreenland),cbind(dat$Year2015,dat$Year2016))
plot(vp)

anova.cca(rda(com~cbind(dat$stationGrcentre,dat$stationGrgreenland)+dat$Year),by="margin",step=1000)
anova.cca(rda(com~cbind(dat$stationGrcentre,dat$stationGrgreenland)+dat$Year),step=1000) 

vp=varpart(com,cbind(dat$stationGrcentre,dat$stationGrgreenland),cbind(dat$Year2015,dat$Year2016),dat$DSP.4)
plot(vp)

anova.cca(rda(com~cbind(dat$stationGrcentre,dat$stationGrgreenland)+cbind(dat$Year2015,dat$Year2016)+dat$DSP.4),step=1000)

anova.cca(rda(com~cbind(dat$stationGrcentre,dat$stationGrgreenland)+cbind(dat$Year2015,dat$Year2016)+dat$DSP.4),step=1000)

anova.cca(rda(com~cbind(dat$stationGrcentre,dat$stationGrgreenland)+dat$DSP.4+dat$Year),step=1000)

vp=varpart(com,cbind(dat$stationGrcentre,dat$stationGrgreenland),cbind(dat$Year2015,dat$Year2016),dat$DSP.4)
plot(vp)

vp=varpart(com,cbind(dat$stationGrcentre,dat$stationGrgreenland),cbind(dat$Year2015,dat$Year2016),dat$DSP.4,dat$chla.Peak.4)
plot(vp)


#abundance by trait
com_prop_seq_fs=com_prop
com_abun=com_prop_seq_fs*rowSums(transect_seq_agg)

samdf_agg=merge(samdf_agg,com_abun,by.x = "row.names",by.y = "row.names")
rownames(samdf_agg)=samdf_agg$Row.names;samdf_agg=samdf_agg[,-1]

com_prop_seq_fs=com_prop

# plot with proportions

ppi=600
png("fs_smooth.png",width =9, height = 7, units = 'in',bg="transparent",res=ppi)
plot_transect(com_prop[,c("mixo","hetero","photo")],samdf_agg[rownames(transect_fs),"DSP.4"],legend=F,f=0.6,ylim=c(0,0.9))
#plot_transect(com_prop[,c(2,3,1)],samdf_agg[rownames(transect_fs),"DSB.4"])
invisible(dev.off())

png("fs_smooth_2014.png",width =9, height = 7, units = 'in',bg="transparent",res=ppi)
sel=samdf_agg[rownames(transect_fs),"Year"]==2014
plot_transect(com_prop[sel,c(2,3,1)],samdf_agg[rownames(transect_fs),"DSP.4"][sel])
dev.off()

png("fs_smooth_2015.png",width =9, height = 7, units = 'in',bg="transparent",res=ppi)
sel=samdf_agg[rownames(transect_fs),"Year"]==2015
plot_transect(com_prop[sel,c(2,3,1)],samdf_agg[rownames(transect_fs),"DSP.4"][sel])
dev.off()

png("fs_smooth_2016.png",width =9, height = 7, units = 'in',bg="transparent",res=ppi)
sel=samdf_agg[rownames(transect_fs),"Year"]==2016
plot_transect(com_prop[sel,c(2,3,1)],samdf_agg[rownames(transect_fs),"DSP.4"][sel])
dev.off()
```


<!---#### Micro--->

```{r trophic_strategy micro, echo=F,fig.keep="none",results="hide"}
library(vegan)

#remove smaller than 15
#transect.sub=transect_seq_agg[,colnames(transect_seq_agg)%in%names(sizeVector[sizeVector>5])]

#remove Phaeocystis
#transect.sub=transect.sub[,!colnames(transect.sub)%in%cw[cw$validName%in%"Phaeocystis_diploid","OTU."]]

fsVector=traitsByOTU(transect_micro_agg,traits,"trophic_strategy",cw_micro,"validName")
transect_fs=mergeByCat(transect_micro_agg,as.factor(fsVector))
transect_fs_hel=decostand(transect_fs,method="hel")
com_prop=prop.table(as.matrix(transect_fs),margin=1)

print(fit <-adonis(transect_fs_hel~DSP.4+DSB.4+Year*stationGr,method="bray",permutations=999,data = samdf_agg[rownames(transect_fs),]))

# plot with proportions

plot_transect(com_prop[,c(2,1,3)],samdf_agg[rownames(transect_fs),"DSP.4"])
plot_transect(com_prop[,c(2,1,3)],samdf_agg[rownames(transect_fs),"DSB.4"])

ppi=600
png("fs_smooth_micro.png",width =9, height = 7, units = 'in',bg="transparent",res=ppi)
plot_transect(com_prop[,c("mixo","hetero","photo")],samdf_agg[rownames(transect_fs),"DSP.4"],legend=F,f=0.6,ylim=c(0,1))
#plot_transect(com_prop[,c(2,3,1)],samdf_agg[rownames(transect_fs),"DSB.4"])
invisible(dev.off())

com_prop_micro_fs=com_prop
fsprop<- function(){
barplot(cbind(apply(com_prop_seq_fs,2,mean),apply(com_prop_micro_fs,2,mean)[match(colnames(com_prop_seq_fs),colnames(com_prop_micro_fs))]), main="",names.arg = c("Sequencage","Micro"),
  xlab="Number of Gears", col=c("#33a02c","#73BAE6","#C7144C"))
  }
png("prop_micro.png",width =5, height = 7, units = 'in',bg="transparent",res=ppi)
barplot(cbind(apply(com_prop_seq_fs,2,mean),apply(com_prop_micro_fs,2,mean)[match(colnames(com_prop_seq_fs),colnames(com_prop_micro_fs))]), main="",names.arg = c("Sequencage","Micro"),
  xlab="Number of Gears", col=c("#33a02c","#73BAE6","#C7144C"))
dev.off()

```


## Classes de taille

```{r classes de tailles seq, echo=F}

classes=c(0.2,2,20,Inf)
sizeClasses=cut(sizeVector,breaks=classes)
names(sizeClasses)=names(sizeVector)
transect_sizeClass=mergeByCat(transect_seq_agg,sizeClasses)
com_prop=prop.table(as.matrix(transect_sizeClass),margin=1)

com_prop_seq_size=com_prop

com_abun=com_prop_seq_size*rowSums(transect_seq_agg)

samdf_agg=merge(samdf_agg,com_abun,by.x = "row.names",by.y = "row.names")
rownames(samdf_agg)=samdf_agg$Row.names;samdf_agg=samdf_agg[,-1]


ppi=600
png("size3_smooth.png",width =9, height = 7, units = 'in',bg="transparent",res=ppi)
plot_transect(com_prop[,c(3,1,2)],samdf_agg[rownames(transect_sizeClass),"DSP.4"],colors=c("#73BAE6","#FFD700","#C742B5"),legend=F)
dev.off()

classes=c(0.2,2,5,10,20,Inf)
sizeClasses=cut(sizeVector,breaks=classes)
names(sizeClasses)=names(sizeVector)
transect_sizeClass=mergeByCat(transect_seq_agg,sizeClasses)

com_prop=prop.table(as.matrix(transect_sizeClass),margin=1)
com_prop_seq_size=com_prop
com_abun=com_prop_seq_size*rowSums(transect_seq_agg)

samdf_agg=merge(samdf_agg,com_abun,by.x = "row.names",by.y = "row.names")
rownames(samdf_agg)=samdf_agg$Row.names;samdf_agg=samdf_agg[,-1]


dat=samdf_agg[rownames(transect_seq_agg),]
com=decostand(com_abun,method="hel")
  
vp=varpart(com,cbind(dat$stationGrcentre,dat$stationGrgreenland),cbind(dat$Year2015,dat$Year2016))
plot(vp)

col=NA
col[dat$stationGrcentre==1]="red"
col[dat$stationGrgreenland==1]="green"
col[is.na(col)]="black"

library(indicspecies)


com=com[,c("(0.2,2]","(2,5]","(5,10]","(10,20]","(20,Inf]")]

indval_outCor(com,factors=dat$Year)
indval_outCor(com,factors=dat$stationGr)






anova.cca(rda(com~cbind(dat$stationGrcentre,dat$stationGrgreenland)+dat$Year),by="margin",step=1000)
anova.cca(rda(com~cbind(dat$stationGrcentre,dat$stationGrgreenland)+dat$Year),step=1000) 

vp=varpart(com,cbind(dat$stationGrcentre,dat$stationGrgreenland),cbind(dat$Year2015,dat$Year2016),dat$DSP.4)
plot(vp)


vp=varpart(com,cbind(dat$stationGrcentre,dat$stationGrgreenland),cbind(dat$Year2015,dat$Year2016),dat$DSP.4,dat$chla.Peak.4)
plot(vp)

anova.cca(rda(com~cbind(dat$stationGrcentre,dat$stationGrgreenland)+dat$DSP.4+dat$Year),by="margin",step=1000)
anova.cca(rda(com~cbind(dat$stationGrcentre,dat$stationGrgreenland)+dat$DSP.4+dat$Year),step=1000)

fs_C1=mergeByCat(transect_seq_agg[,sizeClasses%in%"(0.2,2]"],as.factor(fsVector))
fs_C2=mergeByCat(transect_seq_agg[,sizeClasses%in%"(2,5]"],as.factor(fsVector))
fs_C3=mergeByCat(transect_seq_agg[,sizeClasses%in%"(5,10]"],as.factor(fsVector))
fs_C4=mergeByCat(transect_seq_agg[,sizeClasses%in%"(10,20]"],as.factor(fsVector))
fs_C5=mergeByCat(transect_seq_agg[,sizeClasses%in%"(20,Inf]"],as.factor(fsVector))

rowSums(fs_C1)+rowSums(fs_C2)+rowSums(fs_C3)+rowSums(fs_C4)+rowSums(fs_C5)
rowSums(transect_seq_agg[,!is.na(sizeClasses)])
#unique(transect_sizeClass)
#transect_fs_C1=prop.table(mergeByCat(transect_seq_agg[,sizeClasses%in%"(0.2,2]"],as.factor(fsVector)),margin=1)
prop_fs_C1=fs_C1/ rowSums(transect_seq_agg[,!is.na(sizeClasses)])
#transect_fs_C2=prop.table(mergeByCat(transect_seq_agg[,sizeClasses%in%"(2,5]"],as.factor(fsVector)),margin=1)
prop_fs_C2=fs_C2/ rowSums(transect_seq_agg[,!is.na(sizeClasses)])

#transect_fs_C3=prop.table(mergeByCat(transect_seq_agg[,sizeClasses%in%"(5,10]"],as.factor(fsVector)),margin=1)
prop_fs_C3=fs_C3/ rowSums(transect_seq_agg[,!is.na(sizeClasses)])

#transect_fs_C4=prop.table(mergeByCat(transect_seq_agg[,sizeClasses%in%"(10,20]"],as.factor(fsVector)),margin=1)
prop_fs_C4=fs_C4/ rowSums(transect_seq_agg[,!is.na(sizeClasses)])

#transect_fs_C5=prop.table(mergeByCat(transect_seq_agg[,sizeClasses%in%"(20,Inf]"],as.factor(fsVector)),margin=1)
prop_fs_C5=fs_C5/ rowSums(transect_seq_agg[,!is.na(sizeClasses)])


prop_fs_C1[1,]+prop_fs_C2[1,]+prop_fs_C3[1,]+prop_fs_C4[1,]+prop_fs_C5[1,]


# plot with proportions

ppi=600
png("size5_smooth.png",width =9, height = 7, units = 'in',bg="transparent",res=ppi)
plot_transect(com_prop[,c(4,5,1,2,3)],samdf_agg[rownames(transect_sizeClass),"DSP.4"],legend=F)
dev.off()
#plot_transect(com_prop[,c(4,5,1,2,3)],samdf_agg[rownames(transect_sizeClass),"DSB.4"])


com_prop_seq_size=com_prop

ppi=600
png("figures/prop_fs_C1.png",width =8, height = 4.8, units = 'in',bg="transparent",res=ppi)
plot_transect_small(prop_fs_C1[,c("mixo","hetero","photo")],samdf_agg[rownames(transect_sizeClass),"DSP.4"])
dev.off()

ppi=600
png("figures/prop_fs_C2.png",width =8, height = 4.8, units = 'in',bg="transparent",res=ppi)
plot_transect_small(prop_fs_C2[,c("mixo","hetero","photo")],samdf_agg[rownames(transect_sizeClass),"DSP.4"])
dev.off()
ppi=600
png("figures/prop_fs_C3.png",width =8, height = 4.8, units = 'in',bg="transparent",res=ppi)
plot_transect_small(prop_fs_C3[,c("mixo","hetero","photo")],samdf_agg[rownames(transect_sizeClass),"DSP.4"])
dev.off()

ppi=600
png("figures/prop_fs_C4.png",width =8, height = 4.8, units = 'in',bg="transparent",res=ppi)
plot_transect_small(prop_fs_C4[,c("mixo","hetero","photo")],samdf_agg[rownames(transect_sizeClass),"DSP.4"])
dev.off()

ppi=600
png("figures/prop_fs_C5.png",width =8, height = 4.8, units = 'in',bg="transparent",res=ppi)
plot_transect_small(prop_fs_C5[,c("mixo","hetero","photo")],samdf_agg[rownames(transect_sizeClass),"DSP.4"])
dev.off()

plot_transect_small(fs_C5[,c("mixo","hetero","photo")],samdf_agg[rownames(transect_sizeClass),"DSP.4"])
plot_transect_small(fs_C4[,c("mixo","hetero","photo")],samdf_agg[rownames(transect_sizeClass),"DSP.4"])

```
## Motilité
### Seq
```{r motility seq, echo=F}

motVector=traitsByOTU(transect_seq_agg,traits,"motility",cw_seq,"OTU.")

transect_mot=mergeByCat(transect_seq_agg,as.factor(motVector))

transect_mot_hel=decostand(transect_mot,method="hel")
com_prop=prop.table(as.matrix(transect_mot),margin=1)

com_prop_seq_size=com_prop

com_abun=com_prop_seq_size*rowSums(transect_mot)
colnames(com_abun)=c("Motility0","Motility1")

samdf_agg=merge(samdf_agg,com_abun,by.x = "row.names",by.y = "row.names")
rownames(samdf_agg)=samdf_agg$Row.names;samdf_agg=samdf_agg[,-1]


dat=samdf_agg[rownames(transect_seq_agg),]
com=decostand(com_abun,method="hel")


indval_outCor(com,factors=dat$Year)
indval_outCor(com,factors=dat$stationGr)

ppi=600
png("mot_smooth.png",width =9, height = 7, units = 'in',bg="transparent",res=ppi)
plot_transect(com_prop  ,samdf_agg[rownames(transect_mot),"DSP.4"],legend=F)
dev.off()

vp=varpart(com,cbind(dat$stationGrcentre,dat$stationGrgreenland),cbind(dat$Year2015,dat$Year2016))
plot(vp)

anova.cca(rda(com~cbind(dat$stationGrcentre,dat$stationGrgreenland)+dat$Year),by="margin",step=1000)
anova.cca(rda(com~cbind(dat$stationGrcentre,dat$stationGrgreenland)+dat$Year),step=1000) 

vp=varpart(com,cbind(dat$stationGrcentre,dat$stationGrgreenland),cbind(dat$Year2015,dat$Year2016),dat$DSP.4)
plot(vp)

vp=varpart(transect_mot_hel,cbind(dat$stationGrcentre,dat$stationGrgreenland),cbind(dat$Year2015,dat$Year2016),dat$DSP.4,dat$chla.Peak.4)
plot(vp)

anova.cca(rda(com~cbind(dat$stationGrcentre,dat$stationGrgreenland)+dat$chla.Peak.4+dat$Year),by="margin",step=1000)
anova.cca(rda(com~cbind(dat$stationGrcentre,dat$stationGrgreenland)+dat$DSP.4+dat$Year),step=1000)


```
## DMS
### Sequencage
```{r DMS seq, echo=F}

dmsVector=traitsByOTU(transect_seq_agg,traits,"DMS",cw_seq,"OTU.")
transect_dms=mergeByCat(transect_seq_agg,as.factor(dmsVector))

transect_dms_hel=decostand(transect_dms,method="hel")
com_prop=prop.table(as.matrix(transect_dms),margin=1)

com_abun=com_prop*rowSums(transect_seq_agg)
colnames(com_abun)=c("DMS0","DMS1")

samdf_agg=merge(samdf_agg,com_abun,by.x = "row.names",by.y = "row.names")
rownames(samdf_agg)=samdf_agg$Row.names;samdf_agg=samdf_agg[,-1]

# logit transformation (for percentages)
com_prop.logit=car::logit(com_prop)
# add the minimum (permanova = no negative values)
com_prop.logit=com_prop.logit+abs(min(com_prop.logit))


dat=samdf_agg[rownames(transect_seq_agg),]
com=decostand(com_abun,method="hel")

indval_outCor(com,factors=dat$Year)
indval_outCor(com,factors=dat$stationGr)

vp=varpart(com,cbind(dat$stationGrcentre,dat$stationGrgreenland),cbind(dat$Year2015,dat$Year2016))
plot(vp)

  
vp=varpart(com,cbind(dat$stationGrcentre,dat$stationGrgreenland),cbind(dat$Year2015,dat$Year2016),dat$DSP.4)

#vp=varpart(com,cbind(dat$stationGrcentre,dat$stationGrgreenland),cbind(dat$Year2015,dat$Year2016),dat$DSP.4,dat$chla.Peak)
plot(vp)

plot_transect(com_prop,  samdf_agg[rownames(transect_dms),"DSP.4"],legend=F)


anova.cca(rda(com,cbind(dat$DSP.4),cbind(dat$Year,dat$stationGrcentre,dat$stationGrgreenland)),step=1000)

anova.cca(rda(com,cbind(dat$stationGrcentre,dat$stationGrgreenland),cbind(dat$DSP.4,dat$Year)),step=1000)

anova.cca(rda(com,cbind(dat$Year),cbind(dat$DSP.4,dat$stationGrcentre,dat$stationGrgreenland)),step=1000)

anova.cca(rda(com,cbind(dat$stationGrcentre,dat$stationGrgreenland,dat$DSP.4,dat$Year)),step=1000)

plot(vp)

write.csv(samdf_agg,"data/samdf_agg.csv")
```